spring.application.name=config-service
logging.level.org.springframework.cloud.config.server=ERROR
#logging.level.software.amazon.awssdk=DEBUG
logging.level.com.amazonaws=DEBUG
management.endpoints.web.base-path=/manage
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

