server:
  port: 8888
  host: ${SERVER_HOST:localhost}
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      max: 50
      min: 10

spring:
  application:
    name: config-service
  profiles:
    active: awss3
  cloud:
    config:
      server:
        awss3:
          bucket: test-kunal-pii-logs
          region: ap-southeast-2
          use-directory-layout: true
    retry:
      max-attempts: 6
      initial-interval: 1000
      max-interval: 10000
      multiplier: 2.0

