server:
  port: 8888
  host: ${SERVER_HOST:localhost}
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      max: 50
      min: 10

spring:
  application:
    name: config-service
  profiles:
    active: awss3
  cloud:
    config:
      server:
        awss3:
          bucket:
          region: ap-southeast-2
          prefix: config
    retry:
      max-attempts: 6
      initial-interval: 1000
      max-interval: 10000
      multiplier: 2.0
    bus:
      enabled: true
      retry:
        max-attempts: 6
        initial-interval: 1000
        max-interval: 10000
        multiplier: 2.0
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}          # Default to 'rabbitmq' if not set
    port: ${SPRING_RABBITMQ_PORT:5672}              # Default to 5672 if not set
    username: ${SPRING_RABBITMQ_USERNAME:guest}     # Default to 'guest' if not set
    password: ${SPRING_RABBITMQ_PASSWORD:guest}     # Default to 'guest' if not set
    ssl:
      enabled: ${SPRING_RABBITMQ_SSL_ENABLED:false}
      validate-server-certificate: false
      hostname-verification: false
    retry:
      initial-interval: 5000
      max-interval: 30000
      max-attempts: 10        # Retry up to 10 times


management:
  endpoints:
    web:
      exposure:
        include: busrefresh
