server:
  port: 8888
  host: ${SERVER_HOST:localhost}
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      max: 50
      min: 10
  servlet:
    context-path: /moa/config

spring:
  application:
    name: config-service

  # No need to activate anything here if using on-profile blocks
  profiles:
    active: composite

  cloud:
    config:
      server:
        git:
          enabled: false
        encrypt:
          enabled: false
        failOnCompositeError: true
        prefix: ${config.base.context.path}

# Management endpoints for monitoring
management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh

aws:
  region: ap-southeast-2
  retry:
    max-attempts: 3
    backoff:
      base-delay: 100ms
      max-backoff-time: 20s


---

spring:
  config:
    activate:
      on-profile: dev
  cloud:
    config:
      server:
        composite:
          - type: awssecretsmanager
            region: ap-southeast-2
            prefix: ${config.sm.prefix}
            profileSeparator: /
            order: 1
          - type: awss3
            region: ap-southeast-2
            bucket: dev-config-bucket
            useDirectoryLayout: true
            order: 2

---

spring:
  config:
    activate:
      on-profile: local
  cloud:
    config:
      server:
        composite:
          - type: awssecretsmanager
            region: ap-southeast-2
            prefix: ${config.sm.prefix}
            profileSeparator: ${config.sm.profile.separator}
            order: 1
          - type: awss3
            region: ap-southeast-2
            bucket: ${config.bucket.name}
            useDirectoryLayout: true
            order: 2